stages:
  - test

validate-composer:
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php8.0
  stage: test
  script:
    - composer validate --no-check-publish --no-check-all --no-interaction

lint-php:
  stage: test
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php$PHP_VERSION
  script:
    - find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  parallel:
    matrix:
      - PHP_VERSION: [ '8.1' ]

php-cs-fixer:
  stage: test
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php8.1
  before_script:
    - mkdir -p .composer/cache
    - COMPOSER_CACHE_DIR=.composer/cache composer install
  script:
    - composer phpcsfixer
  cache:
    key: composer-cache
    paths:
      - .composer/cache

phpstan-v11:
  image: registry.gitlab.com/codemonkey1988/docker-composer-image:2-php$PHP_VERSION
  stage: test
  before_script:
    - mkdir -p .composer/cache
    - composer require --no-interaction --no-ansi --no-progress --no-install typo3/cms-core:^12.4
    - composer require --no-interaction --no-ansi --no-progress --no-install typo3/cms-filemetadata:^12.4
    - composer require --no-interaction --no-ansi --no-progress --no-install typo3/cms-filelist:^12.4
    - COMPOSER_CACHE_DIR=.composer/cache composer install
  # TODO: Muss überarbeitet werden
  script:
    - echo "PHPStan check temporarily disabled"
  parallel:
    matrix:
      - PHP_VERSION: [ '8.1' ]
  cache:
    key: composer-cache
    paths:
      - .composer/cache
