services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fairway\CantoSaasFal\:
    resource: '../Classes/*'

  Fairway\CantoSaasFal\Browser\CantoAssetBrowser:
    shared: false
    public: true

  Fairway\CantoSaasFal\Hooks\DataHandlerHooks:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  Fairway\CantoSaasFal\Resource\Repository\CantoRepository:
    public: true
    arguments:
      - '@TYPO3\CMS\Core\Registry'
      - '@cache.canto_folder'
      - '@cache.canto_file'

  Fairway\CantoSaasFal\Resource\Metadata\Extractor:
    public: true

  Fairway\CantoSaasFal\Resource\Processing\CantoPreviewProcessor:
    public: true

  Fairway\CantoSaasFal\Resource\Processing\CantoMdcProcessor:
    public: true

  Fairway\CantoSaasFal\Controller\Backend\CantoAssetBrowserController:
    public: true

  Fairway\CantoSaasFal\Resource\MdcUrlGenerator:
    public: true

  Fairway\CantoSaasFal\Resource\Metadata\Exporter:
    public: true

  Fairway\CantoSaasFal\Resource\Repository\CantoAlbumRepository:
    arguments:
      - 'sys_file_canto_album'
      - '@TYPO3\CMS\Core\Database\ConnectionPool'

  Fairway\CantoSaasFal\Command\WarmupCantoCache:
    calls:
      - injectStorageRepository: ['@TYPO3\CMS\Core\Resource\StorageRepository']
      - injectCantoFolderCache: ['@cache.canto_folder']
    tags:
      - name: 'console.command'
        command: 'canto:warmupcache'

  Fairway\CantoSaasFal\Command\UpdateMetadataAssetsCommand:
    calls:
      - injectCantoFileCache: [ '@cache.canto_file' ]
    tags:
      - name: 'console.command'
        command: 'canto:updatemetadataassets'

  Fairway\CantoSaasFal\Command\UpdateImageAssetsUsedInFrontendCommand:
    calls:
      - injectCantoFileCache: ['@cache.canto_file']
    tags:
      - name: 'console.command'
        command: 'canto:updateusedmetadataassets'

  Fairway\CantoSaasFal\Command\RemoveMdcPrefixForFilesCommand:
    tags:
      - name: 'console.command'
        command: 'canto:removemdcprefixforfiles'

  Fairway\CantoSaasFal\Command\MigrateFileIdentifiersToNewFormat:
    tags:
      - name: 'console.command'
        command: 'canto:migratefileidentifiers'

  Fairway\CantoSaasFal\Resource\EventListener\HandleMultipleFolders:
    tags:
      - name: event.listener
        identifier: updateFoldersAfterFileAddedToIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent
        method: afterFileAddedToIndexEvent
      - name: event.listener
        identifier: updateFoldersAfterFileUpdatedInIndexEvent
        event: TYPO3\CMS\Core\Resource\Event\AfterFileUpdatedInIndexEvent
        method: afterFileUpdatedInIndexEvent

  Fairway\CantoSaasFal\Resource\EventListener\GeneratePublicUrlForResourceEventListener:
    tags:
      - name: event.listener
        identifier: generatePublicUrlForMdcFiles
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent

  Fairway\CantoSaasFal\Resource\EventListener\ForceJpgPreviewImage:
    tags:
      - name: event.listener
        identifier: forceCantoJpegPreview
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  Fairway\CantoSaasFal\Resource\EventListener\MetadataWebhookEventListener:
    tags:
      - name: event.listener
        identifier: metadataWebhookEventListener
        event: Fairway\CantoSaasFal\Resource\Event\IncomingWebhookEvent

  Fairway\CantoSaasFal\Resource\EventListener\NewAssetVersionWebhookEventListener:
    tags:
      - name: event.listener
        identifier: newAssetVersionWebhookEventListener
        event: Fairway\CantoSaasFal\Resource\Event\IncomingWebhookEvent

  Fairway\CantoSaasFal\Resource\EventListener\DeleteAssetWebhookEventListener:
    tags:
      - name: event.listener
        identifier: deleteAssetWebhookEventListener
        event: Fairway\CantoSaasFal\Resource\Event\IncomingWebhookEvent

  Fairway\CantoSaasFal\Resource\EventListener\BeforeFileProcessingEventListener:
    arguments:
      - "@Fairway\\CantoSaasFal\\Resource\\Repository\\CantoRepository"
      - "@TYPO3\\CMS\\Core\\Resource\\ProcessedFileRepository"
      - "@Fairway\\CantoSaasFal\\Resource\\MdcUrlGenerator"
    tags:
      - name: event.listener
        identifier: cantoMdcProcessingFileEnricher
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent

  Fairway\CantoSaasFal\Resource\EventListener\AfterFormEnginePageInitializedEventListener:
    tags:
      - name: event.listener
        identifier: afterFormEnginePageInitializedEventListener
        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent


  Fairway\CantoSaasFal\Resource\EventListener\SyncMetaDataCategoriesEventListener:
    tags:
      - name: event.listener
        identifier: 'synchronizeFileMetaDataCategoriesAfterCreation'
        method: 'afterFileMetaDataCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent
      - name: event.listener
        identifier: 'synchronizeFileMetaDataCategoriesAfterUpdate'
        method: 'afterFileMetaDataUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent

  Fairway\CantoSaasFal\Resource\EventListener\SyncMetaDataTranslationsEventListener:
    tags:
      - name: event.listener
        identifier: 'synchronizeFileMetaDataTranslationsAfterCreation'
        method: 'afterFileMetaDataCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent
      - name: event.listener
        identifier: 'synchronizeFileMetaDataTranslationsAfterUpdate'
        method: 'afterFileMetaDataUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent


  cache.canto_folder:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['canto_saas_fal_folder']

  cache.canto_file:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    public: true
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'canto_saas_fal_file' ]
